//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InvertoryHelper.Droid.ExchangeReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExchangeERP_MobAppSoapBinding", Namespace="http://astelit.com.ua")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Object))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Header))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ЕдиницаИзмерения))]
    public partial class ExchangeERP_MobApp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNomenklaturesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMeasuresOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoragesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNomenklaturesKindOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCharacteristicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBarcodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPricesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendRecountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMinVersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExchangeERP_MobApp() {
            this.Url = "http://193.93.76.208:8080/erp_dev1/ws/ExchangeERP_MobApp.1cws";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNomenklaturesCompletedEventHandler GetNomenklaturesCompleted;
        
        /// <remarks/>
        public event GetMeasuresCompletedEventHandler GetMeasuresCompleted;
        
        /// <remarks/>
        public event GetStoragesCompletedEventHandler GetStoragesCompleted;
        
        /// <remarks/>
        public event GetNomenklaturesKindCompletedEventHandler GetNomenklaturesKindCompleted;
        
        /// <remarks/>
        public event GetCharacteristicsCompletedEventHandler GetCharacteristicsCompleted;
        
        /// <remarks/>
        public event GetBarcodesCompletedEventHandler GetBarcodesCompleted;
        
        /// <remarks/>
        public event GetPricesCompletedEventHandler GetPricesCompleted;
        
        /// <remarks/>
        public event SendRecountsCompletedEventHandler SendRecountsCompleted;
        
        /// <remarks/>
        public event SendOrdersCompletedEventHandler SendOrdersCompleted;
        
        /// <remarks/>
        public event GetRecountsCompletedEventHandler GetRecountsCompleted;
        
        /// <remarks/>
        public event GetPasswordCompletedEventHandler GetPasswordCompleted;
        
        /// <remarks/>
        public event GetMinVersionCompletedEventHandler GetMinVersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetNomenklatures", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Номенклатура[] GetNomenklatures(string NodeId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> DeleteRegistration) {
            object[] results = this.Invoke("GetNomenklatures", new object[] {
                        NodeId,
                        DeleteRegistration});
            return ((Номенклатура[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNomenklaturesAsync(string NodeId, System.Nullable<bool> DeleteRegistration) {
            this.GetNomenklaturesAsync(NodeId, DeleteRegistration, null);
        }
        
        /// <remarks/>
        public void GetNomenklaturesAsync(string NodeId, System.Nullable<bool> DeleteRegistration, object userState) {
            if ((this.GetNomenklaturesOperationCompleted == null)) {
                this.GetNomenklaturesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNomenklaturesOperationCompleted);
            }
            this.InvokeAsync("GetNomenklatures", new object[] {
                        NodeId,
                        DeleteRegistration}, this.GetNomenklaturesOperationCompleted, userState);
        }
        
        private void OnGetNomenklaturesOperationCompleted(object arg) {
            if ((this.GetNomenklaturesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNomenklaturesCompleted(this, new GetNomenklaturesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetMeasures", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ЕдиницаИзмерения", IsNullable=false)]
        public object[] GetMeasures(string NodeId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> DeleteRegistration) {
            object[] results = this.Invoke("GetMeasures", new object[] {
                        NodeId,
                        DeleteRegistration});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMeasuresAsync(string NodeId, System.Nullable<bool> DeleteRegistration) {
            this.GetMeasuresAsync(NodeId, DeleteRegistration, null);
        }
        
        /// <remarks/>
        public void GetMeasuresAsync(string NodeId, System.Nullable<bool> DeleteRegistration, object userState) {
            if ((this.GetMeasuresOperationCompleted == null)) {
                this.GetMeasuresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMeasuresOperationCompleted);
            }
            this.InvokeAsync("GetMeasures", new object[] {
                        NodeId,
                        DeleteRegistration}, this.GetMeasuresOperationCompleted, userState);
        }
        
        private void OnGetMeasuresOperationCompleted(object arg) {
            if ((this.GetMeasuresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMeasuresCompleted(this, new GetMeasuresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetStorages", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Склад[] GetStorages(string NodeId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> DeleteRegistration) {
            object[] results = this.Invoke("GetStorages", new object[] {
                        NodeId,
                        DeleteRegistration});
            return ((Склад[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStoragesAsync(string NodeId, System.Nullable<bool> DeleteRegistration) {
            this.GetStoragesAsync(NodeId, DeleteRegistration, null);
        }
        
        /// <remarks/>
        public void GetStoragesAsync(string NodeId, System.Nullable<bool> DeleteRegistration, object userState) {
            if ((this.GetStoragesOperationCompleted == null)) {
                this.GetStoragesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoragesOperationCompleted);
            }
            this.InvokeAsync("GetStorages", new object[] {
                        NodeId,
                        DeleteRegistration}, this.GetStoragesOperationCompleted, userState);
        }
        
        private void OnGetStoragesOperationCompleted(object arg) {
            if ((this.GetStoragesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoragesCompleted(this, new GetStoragesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetNomenklaturesKind", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ВидНоменклатуры[] GetNomenklaturesKind(string NodeId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> DeleteRegistration) {
            object[] results = this.Invoke("GetNomenklaturesKind", new object[] {
                        NodeId,
                        DeleteRegistration});
            return ((ВидНоменклатуры[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNomenklaturesKindAsync(string NodeId, System.Nullable<bool> DeleteRegistration) {
            this.GetNomenklaturesKindAsync(NodeId, DeleteRegistration, null);
        }
        
        /// <remarks/>
        public void GetNomenklaturesKindAsync(string NodeId, System.Nullable<bool> DeleteRegistration, object userState) {
            if ((this.GetNomenklaturesKindOperationCompleted == null)) {
                this.GetNomenklaturesKindOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNomenklaturesKindOperationCompleted);
            }
            this.InvokeAsync("GetNomenklaturesKind", new object[] {
                        NodeId,
                        DeleteRegistration}, this.GetNomenklaturesKindOperationCompleted, userState);
        }
        
        private void OnGetNomenklaturesKindOperationCompleted(object arg) {
            if ((this.GetNomenklaturesKindCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNomenklaturesKindCompleted(this, new GetNomenklaturesKindCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetCharacteristics", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ХарактеристикаНоменклатуры[] GetCharacteristics(string NodeId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> DeleteRegistration) {
            object[] results = this.Invoke("GetCharacteristics", new object[] {
                        NodeId,
                        DeleteRegistration});
            return ((ХарактеристикаНоменклатуры[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCharacteristicsAsync(string NodeId, System.Nullable<bool> DeleteRegistration) {
            this.GetCharacteristicsAsync(NodeId, DeleteRegistration, null);
        }
        
        /// <remarks/>
        public void GetCharacteristicsAsync(string NodeId, System.Nullable<bool> DeleteRegistration, object userState) {
            if ((this.GetCharacteristicsOperationCompleted == null)) {
                this.GetCharacteristicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCharacteristicsOperationCompleted);
            }
            this.InvokeAsync("GetCharacteristics", new object[] {
                        NodeId,
                        DeleteRegistration}, this.GetCharacteristicsOperationCompleted, userState);
        }
        
        private void OnGetCharacteristicsOperationCompleted(object arg) {
            if ((this.GetCharacteristicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCharacteristicsCompleted(this, new GetCharacteristicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetBarcodes", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Штрихкод")]
        public СтрокаШтрихкод[] GetBarcodes(string NodeId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> DeleteRegistration) {
            object[] results = this.Invoke("GetBarcodes", new object[] {
                        NodeId,
                        DeleteRegistration});
            return ((СтрокаШтрихкод[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBarcodesAsync(string NodeId, System.Nullable<bool> DeleteRegistration) {
            this.GetBarcodesAsync(NodeId, DeleteRegistration, null);
        }
        
        /// <remarks/>
        public void GetBarcodesAsync(string NodeId, System.Nullable<bool> DeleteRegistration, object userState) {
            if ((this.GetBarcodesOperationCompleted == null)) {
                this.GetBarcodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBarcodesOperationCompleted);
            }
            this.InvokeAsync("GetBarcodes", new object[] {
                        NodeId,
                        DeleteRegistration}, this.GetBarcodesOperationCompleted, userState);
        }
        
        private void OnGetBarcodesOperationCompleted(object arg) {
            if ((this.GetBarcodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBarcodesCompleted(this, new GetBarcodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetPrices", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string GetPrices(string NodeId, string StrogageUID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> DeleteRegistration) {
            object[] results = this.Invoke("GetPrices", new object[] {
                        NodeId,
                        StrogageUID,
                        DeleteRegistration});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPricesAsync(string NodeId, string StrogageUID, System.Nullable<bool> DeleteRegistration) {
            this.GetPricesAsync(NodeId, StrogageUID, DeleteRegistration, null);
        }
        
        /// <remarks/>
        public void GetPricesAsync(string NodeId, string StrogageUID, System.Nullable<bool> DeleteRegistration, object userState) {
            if ((this.GetPricesOperationCompleted == null)) {
                this.GetPricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPricesOperationCompleted);
            }
            this.InvokeAsync("GetPrices", new object[] {
                        NodeId,
                        StrogageUID,
                        DeleteRegistration}, this.GetPricesOperationCompleted, userState);
        }
        
        private void OnGetPricesOperationCompleted(object arg) {
            if ((this.GetPricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPricesCompleted(this, new GetPricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:SendRecounts", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string SendRecounts([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("Documents")] Document[] DocumentList) {
            object[] results = this.Invoke("SendRecounts", new object[] {
                        DocumentList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendRecountsAsync(Document[] DocumentList) {
            this.SendRecountsAsync(DocumentList, null);
        }
        
        /// <remarks/>
        public void SendRecountsAsync(Document[] DocumentList, object userState) {
            if ((this.SendRecountsOperationCompleted == null)) {
                this.SendRecountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendRecountsOperationCompleted);
            }
            this.InvokeAsync("SendRecounts", new object[] {
                        DocumentList}, this.SendRecountsOperationCompleted, userState);
        }
        
        private void OnSendRecountsOperationCompleted(object arg) {
            if ((this.SendRecountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendRecountsCompleted(this, new SendRecountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:SendOrders", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string SendOrders([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("Documents")] Document[] DocumentList) {
            object[] results = this.Invoke("SendOrders", new object[] {
                        DocumentList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOrdersAsync(Document[] DocumentList) {
            this.SendOrdersAsync(DocumentList, null);
        }
        
        /// <remarks/>
        public void SendOrdersAsync(Document[] DocumentList, object userState) {
            if ((this.SendOrdersOperationCompleted == null)) {
                this.SendOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrdersOperationCompleted);
            }
            this.InvokeAsync("SendOrders", new object[] {
                        DocumentList}, this.SendOrdersOperationCompleted, userState);
        }
        
        private void OnSendOrdersOperationCompleted(object arg) {
            if ((this.SendOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrdersCompleted(this, new SendOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetRecounts", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Documents")]
        public Document[] GetRecounts(string NodeId, string StrogageUID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> DeleteRegistration) {
            object[] results = this.Invoke("GetRecounts", new object[] {
                        NodeId,
                        StrogageUID,
                        DeleteRegistration});
            return ((Document[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRecountsAsync(string NodeId, string StrogageUID, System.Nullable<bool> DeleteRegistration) {
            this.GetRecountsAsync(NodeId, StrogageUID, DeleteRegistration, null);
        }
        
        /// <remarks/>
        public void GetRecountsAsync(string NodeId, string StrogageUID, System.Nullable<bool> DeleteRegistration, object userState) {
            if ((this.GetRecountsOperationCompleted == null)) {
                this.GetRecountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecountsOperationCompleted);
            }
            this.InvokeAsync("GetRecounts", new object[] {
                        NodeId,
                        StrogageUID,
                        DeleteRegistration}, this.GetRecountsOperationCompleted, userState);
        }
        
        private void OnGetRecountsOperationCompleted(object arg) {
            if ((this.GetRecountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecountsCompleted(this, new GetRecountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetPassword", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string GetPassword() {
            object[] results = this.Invoke("GetPassword", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPasswordAsync() {
            this.GetPasswordAsync(null);
        }
        
        /// <remarks/>
        public void GetPasswordAsync(object userState) {
            if ((this.GetPasswordOperationCompleted == null)) {
                this.GetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPasswordOperationCompleted);
            }
            this.InvokeAsync("GetPassword", new object[0], this.GetPasswordOperationCompleted, userState);
        }
        
        private void OnGetPasswordOperationCompleted(object arg) {
            if ((this.GetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPasswordCompleted(this, new GetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://astelit.com.ua#ExchangeERP_MobApp:GetMinVersion", RequestNamespace="http://astelit.com.ua", ResponseNamespace="http://astelit.com.ua", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="integer")]
        public string GetMinVersion() {
            object[] results = this.Invoke("GetMinVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMinVersionAsync() {
            this.GetMinVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetMinVersionAsync(object userState) {
            if ((this.GetMinVersionOperationCompleted == null)) {
                this.GetMinVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMinVersionOperationCompleted);
            }
            this.InvokeAsync("GetMinVersion", new object[0], this.GetMinVersionOperationCompleted, userState);
        }
        
        private void OnGetMinVersionOperationCompleted(object arg) {
            if ((this.GetMinVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMinVersionCompleted(this, new GetMinVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class Номенклатура {
        
        private string ссылкаField;
        
        private string кодField;
        
        private string наименованиеField;
        
        private string родительField;
        
        private bool этоГруппаField;
        
        private string видНоменклатурыField;
        
        private string единицаИзмеренияField;
        
        private System.Nullable<ПеречислениеВариантИспользованияХарактеристикНоменклатуры> вариантИспользованияХарактеристикField;
        
        private bool вариантИспользованияХарактеристикFieldSpecified;
        
        private bool пометкаУдаленияField;
        
        private string артикулField;
        
        /// <remarks/>
        public string Ссылка {
            get {
                return this.ссылкаField;
            }
            set {
                this.ссылкаField = value;
            }
        }
        
        /// <remarks/>
        public string Код {
            get {
                return this.кодField;
            }
            set {
                this.кодField = value;
            }
        }
        
        /// <remarks/>
        public string Наименование {
            get {
                return this.наименованиеField;
            }
            set {
                this.наименованиеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Родитель {
            get {
                return this.родительField;
            }
            set {
                this.родительField = value;
            }
        }
        
        /// <remarks/>
        public bool ЭтоГруппа {
            get {
                return this.этоГруппаField;
            }
            set {
                this.этоГруппаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ВидНоменклатуры {
            get {
                return this.видНоменклатурыField;
            }
            set {
                this.видНоменклатурыField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ЕдиницаИзмерения {
            get {
                return this.единицаИзмеренияField;
            }
            set {
                this.единицаИзмеренияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<ПеречислениеВариантИспользованияХарактеристикНоменклатуры> ВариантИспользованияХарактеристик {
            get {
                return this.вариантИспользованияХарактеристикField;
            }
            set {
                this.вариантИспользованияХарактеристикField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ВариантИспользованияХарактеристикSpecified {
            get {
                return this.вариантИспользованияХарактеристикFieldSpecified;
            }
            set {
                this.вариантИспользованияХарактеристикFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ПометкаУдаления {
            get {
                return this.пометкаУдаленияField;
            }
            set {
                this.пометкаУдаленияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Артикул {
            get {
                return this.артикулField;
            }
            set {
                this.артикулField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Перечисление.ВариантИспользованияХарактеристикНоменклатуры", Namespace="http://astelit.com.ua")]
    public enum ПеречислениеВариантИспользованияХарактеристикНоменклатуры {
        
        /// <remarks/>
        НеИспользовать,
        
        /// <remarks/>
        ОбщиеДляВидаНоменклатуры,
        
        /// <remarks/>
        ИндивидуальныеДляНоменклатуры,
        
        /// <remarks/>
        ОбщиеСДругимВидомНоменклатуры,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.1c.ru/SSL/Exchange/Message")]
    public abstract partial class Object {
        
        private object additionalInfoField;
        
        /// <remarks/>
        public object AdditionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.1c.ru/SSL/Exchange/Message")]
    public partial class Header {
        
        private string formatField;
        
        private System.DateTime creationDateField;
        
        private Confirmation confirmationField;
        
        private string[] availableVersionField;
        
        /// <remarks/>
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        public Confirmation Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvailableVersion")]
        public string[] AvailableVersion {
            get {
                return this.availableVersionField;
            }
            set {
                this.availableVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.1c.ru/SSL/Exchange/Message")]
    public partial class Confirmation {
        
        private string exchangePlanField;
        
        private string toField;
        
        private string fromField;
        
        private string messageNoField;
        
        private string receivedNoField;
        
        /// <remarks/>
        public string ExchangePlan {
            get {
                return this.exchangePlanField;
            }
            set {
                this.exchangePlanField = value;
            }
        }
        
        /// <remarks/>
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MessageNo {
            get {
                return this.messageNoField;
            }
            set {
                this.messageNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ReceivedNo {
            get {
                return this.receivedNoField;
            }
            set {
                this.receivedNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class СтрокаШтрихкод {
        
        private string штрихкодField;
        
        private string номенклатураField;
        
        private string характеристикаНоменклатурыField;
        
        private string единицаИзмеренияField;
        
        private bool удалениеField;
        
        /// <remarks/>
        public string Штрихкод {
            get {
                return this.штрихкодField;
            }
            set {
                this.штрихкодField = value;
            }
        }
        
        /// <remarks/>
        public string Номенклатура {
            get {
                return this.номенклатураField;
            }
            set {
                this.номенклатураField = value;
            }
        }
        
        /// <remarks/>
        public string ХарактеристикаНоменклатуры {
            get {
                return this.характеристикаНоменклатурыField;
            }
            set {
                this.характеристикаНоменклатурыField = value;
            }
        }
        
        /// <remarks/>
        public string ЕдиницаИзмерения {
            get {
                return this.единицаИзмеренияField;
            }
            set {
                this.единицаИзмеренияField = value;
            }
        }
        
        /// <remarks/>
        public bool Удаление {
            get {
                return this.удалениеField;
            }
            set {
                this.удалениеField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class СтрокаЦена {
        
        private string номенклатураField;
        
        private string характеристикаНоменклатурыField;
        
        private decimal ценаField;
        
        private bool удалениеField;
        
        /// <remarks/>
        public string Номенклатура {
            get {
                return this.номенклатураField;
            }
            set {
                this.номенклатураField = value;
            }
        }
        
        /// <remarks/>
        public string ХарактеристикаНоменклатуры {
            get {
                return this.характеристикаНоменклатурыField;
            }
            set {
                this.характеристикаНоменклатурыField = value;
            }
        }
        
        /// <remarks/>
        public decimal Цена {
            get {
                return this.ценаField;
            }
            set {
                this.ценаField = value;
            }
        }
        
        /// <remarks/>
        public bool Удаление {
            get {
                return this.удалениеField;
            }
            set {
                this.удалениеField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class ХарактеристикаНоменклатуры {
        
        private string ссылкаField;
        
        private string наименованиеField;
        
        private string владелецField;
        
        private bool пометкаУдаленияField;
        
        /// <remarks/>
        public string Ссылка {
            get {
                return this.ссылкаField;
            }
            set {
                this.ссылкаField = value;
            }
        }
        
        /// <remarks/>
        public string Наименование {
            get {
                return this.наименованиеField;
            }
            set {
                this.наименованиеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Владелец {
            get {
                return this.владелецField;
            }
            set {
                this.владелецField = value;
            }
        }
        
        /// <remarks/>
        public bool ПометкаУдаления {
            get {
                return this.пометкаУдаленияField;
            }
            set {
                this.пометкаУдаленияField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class Склад {
        
        private string ссылкаField;
        
        private string наименованиеField;
        
        private string родительField;
        
        private bool этоГруппаField;
        
        private bool пометкаУдаленияField;
        
        /// <remarks/>
        public string Ссылка {
            get {
                return this.ссылкаField;
            }
            set {
                this.ссылкаField = value;
            }
        }
        
        /// <remarks/>
        public string Наименование {
            get {
                return this.наименованиеField;
            }
            set {
                this.наименованиеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Родитель {
            get {
                return this.родительField;
            }
            set {
                this.родительField = value;
            }
        }
        
        /// <remarks/>
        public bool ЭтоГруппа {
            get {
                return this.этоГруппаField;
            }
            set {
                this.этоГруппаField = value;
            }
        }
        
        /// <remarks/>
        public bool ПометкаУдаления {
            get {
                return this.пометкаУдаленияField;
            }
            set {
                this.пометкаУдаленияField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class ЕдиницаИзмерения {
        
        private string ссылкаField;
        
        private string кодField;
        
        private string наименованиеField;
        
        private string номенклатураField;
        
        private bool пометкаУдаленияField;
        
        private decimal числительField;
        
        /// <remarks/>
        public string Ссылка {
            get {
                return this.ссылкаField;
            }
            set {
                this.ссылкаField = value;
            }
        }
        
        /// <remarks/>
        public string Код {
            get {
                return this.кодField;
            }
            set {
                this.кодField = value;
            }
        }
        
        /// <remarks/>
        public string Наименование {
            get {
                return this.наименованиеField;
            }
            set {
                this.наименованиеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Номенклатура {
            get {
                return this.номенклатураField;
            }
            set {
                this.номенклатураField = value;
            }
        }
        
        /// <remarks/>
        public bool ПометкаУдаления {
            get {
                return this.пометкаУдаленияField;
            }
            set {
                this.пометкаУдаленияField = value;
            }
        }
        
        /// <remarks/>
        public decimal Числитель {
            get {
                return this.числительField;
            }
            set {
                this.числительField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class ВидНоменклатуры {
        
        private string ссылкаField;
        
        private string наименованиеField;
        
        private string родительField;
        
        private bool этоГруппаField;
        
        private bool пометкаУдаленияField;
        
        /// <remarks/>
        public string Ссылка {
            get {
                return this.ссылкаField;
            }
            set {
                this.ссылкаField = value;
            }
        }
        
        /// <remarks/>
        public string Наименование {
            get {
                return this.наименованиеField;
            }
            set {
                this.наименованиеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Родитель {
            get {
                return this.родительField;
            }
            set {
                this.родительField = value;
            }
        }
        
        /// <remarks/>
        public bool ЭтоГруппа {
            get {
                return this.этоГруппаField;
            }
            set {
                this.этоГруппаField = value;
            }
        }
        
        /// <remarks/>
        public bool ПометкаУдаления {
            get {
                return this.пометкаУдаленияField;
            }
            set {
                this.пометкаУдаленияField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class DocumentString {
        
        private string countField;
        
        private string nomenklatureField;
        
        private string charakteristicField;
        
        private string unitField;
        
        private System.Nullable<decimal> qtyField;
        
        private bool qtyFieldSpecified;
        
        private System.Nullable<decimal> priceField;
        
        private bool priceFieldSpecified;
        
        private System.Nullable<decimal> sumField;
        
        private bool sumFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string Nomenklature {
            get {
                return this.nomenklatureField;
            }
            set {
                this.nomenklatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Charakteristic {
            get {
                return this.charakteristicField;
            }
            set {
                this.charakteristicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified {
            get {
                return this.qtyFieldSpecified;
            }
            set {
                this.qtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SumSpecified {
            get {
                return this.sumFieldSpecified;
            }
            set {
                this.sumFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astelit.com.ua")]
    public partial class Document {
        
        private string uIDField;
        
        private string numberField;
        
        private System.DateTime dateTimeField;
        
        private string strogageField;
        
        private System.Nullable<decimal> summField;
        
        private bool summFieldSpecified;
        
        private string baseDocumentField;
        
        private System.Nullable<System.DateTime> arrivalDateField;
        
        private bool arrivalDateFieldSpecified;
        
        private string commentField;
        
        private DocumentString[] tableField;
        
        private bool deletionMarkField;
        
        private bool postedField;
        
        /// <remarks/>
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Strogage {
            get {
                return this.strogageField;
            }
            set {
                this.strogageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Summ {
            get {
                return this.summField;
            }
            set {
                this.summField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SummSpecified {
            get {
                return this.summFieldSpecified;
            }
            set {
                this.summFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BaseDocument {
            get {
                return this.baseDocumentField;
            }
            set {
                this.baseDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> ArrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                this.arrivalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArrivalDateSpecified {
            get {
                return this.arrivalDateFieldSpecified;
            }
            set {
                this.arrivalDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Table", IsNullable=true)]
        public DocumentString[] Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        public bool DeletionMark {
            get {
                return this.deletionMarkField;
            }
            set {
                this.deletionMarkField = value;
            }
        }
        
        /// <remarks/>
        public bool Posted {
            get {
                return this.postedField;
            }
            set {
                this.postedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetNomenklaturesCompletedEventHandler(object sender, GetNomenklaturesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNomenklaturesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNomenklaturesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Номенклатура[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Номенклатура[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetMeasuresCompletedEventHandler(object sender, GetMeasuresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMeasuresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMeasuresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetStoragesCompletedEventHandler(object sender, GetStoragesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoragesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoragesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Склад[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Склад[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetNomenklaturesKindCompletedEventHandler(object sender, GetNomenklaturesKindCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNomenklaturesKindCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNomenklaturesKindCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ВидНоменклатуры[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ВидНоменклатуры[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetCharacteristicsCompletedEventHandler(object sender, GetCharacteristicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCharacteristicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCharacteristicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ХарактеристикаНоменклатуры[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ХарактеристикаНоменклатуры[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBarcodesCompletedEventHandler(object sender, GetBarcodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBarcodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBarcodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public СтрокаШтрихкод[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((СтрокаШтрихкод[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetPricesCompletedEventHandler(object sender, GetPricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SendRecountsCompletedEventHandler(object sender, SendRecountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendRecountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendRecountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SendOrdersCompletedEventHandler(object sender, SendOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetRecountsCompletedEventHandler(object sender, GetRecountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Document[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Document[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetPasswordCompletedEventHandler(object sender, GetPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetMinVersionCompletedEventHandler(object sender, GetMinVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMinVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMinVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591